{"topicSections":[{"generated":true,"title":"Articles","identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKit"]},{"title":"Classes","identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitFilesDataService","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitManager","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitObserver","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitReader","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitService","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitWriter"]},{"title":"Protocols","identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ObjectType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Payload","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Sample","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SampleType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/UnitConvertable"]},{"title":"Structures","identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummary","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Category","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Characteristic","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Correlation","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DeletedObject","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Device","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Electrocardiogram","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthDataOperationResult","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitAccountDataProvider","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitConfiguration","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HeartbeatSeries","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/PreferredUnit","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Quantity","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Source","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SourceRevision","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Statistics","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/VisionPrescription","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Workout","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutConfiguration","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutEvent","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutRoute"]},{"identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummaryCompletionHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummaryQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Anchor","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/AnchoredObjectQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/AnchoredResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CategoryResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationCompletionHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DeletionCompletionBlock","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ElectrocardiogramResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HeartbeatSeriesResultsDataHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ObserverQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ObserverUpdateHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/PreferredUnitsCompeltion","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/QuantityResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Query","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SampleQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SampleResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SourceCompletionHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SourceQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatisticsCollectionQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatisticsCompletionHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatisticsQuery","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatusCompletionBlock","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutResultsHandler","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutRouteResultsDataHandler"],"title":"Type Aliases"},{"identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummaryType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CategoryType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CharacteristicType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DocumentType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ElectrocardiogramType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Metadata","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/QuantityType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SeriesType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/UpdateFrequency","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/VisionPrescriptionType","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutType"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Foundation","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKit","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Swift"]}],"variants":[{"paths":["\/documentation\/digimehealthkit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/digimehealthkit"]}],"sections":[],"metadata":{"role":"collection","roleHeading":"Framework","modules":[{"name":"DigiMeHealthKit"}],"title":"DigiMeHealthKit","externalID":"DigiMeHealthKit","symbolKind":"module"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"references":{"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Anchor":{"abstract":[{"type":"text","text":"*"},{"inlineContent":[{"type":"text","text":"HKQueryAnchor"}],"type":"strong"},{"text":" typealias","type":"text"}],"navigatorTitle":[{"text":"Anchor","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Anchor","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Anchor"}],"kind":"symbol","role":"symbol","title":"Anchor","url":"\/documentation\/digimehealthkit\/anchor"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitConfiguration":{"url":"\/documentation\/digimehealthkit\/healthkitconfiguration","title":"HealthKitConfiguration","type":"topic","abstract":[],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"HealthKitConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"HealthKitConfiguration","kind":"identifier"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/DigiMeHealthKitVersionNumber":{"type":"topic","title":"DigiMeHealthKitVersionNumber","kind":"symbol","abstract":[{"text":"Project version number for DigiMeHealthKit.","type":"text"}],"url":"\/documentation\/digimehealthkit\/digimehealthkitversionnumber","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKitVersionNumber","fragments":[{"kind":"identifier","text":"DigiMeHealthKitVersionNumber"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ObserverQuery":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ObserverQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ObserverQuery"}],"type":"topic","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"HKObserverQuery"}]},{"type":"text","text":" typealias"}],"kind":"symbol","url":"\/documentation\/digimehealthkit\/observerquery","title":"ObserverQuery","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ObserverQuery","role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/DeletionCompletionBlock":{"type":"topic","title":"DeletionCompletionBlock","kind":"symbol","abstract":[],"url":"\/documentation\/digimehealthkit\/deletioncompletionblock","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DeletionCompletionBlock","navigatorTitle":[{"text":"DeletionCompletionBlock","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeletionCompletionBlock"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitAccountDataProvider":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitAccountDataProvider","title":"HealthKitAccountDataProvider","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HealthKitAccountDataProvider","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/healthkitaccountdataprovider","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"HealthKitAccountDataProvider","kind":"identifier"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/VisionPrescription":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisionPrescription","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/visionprescription","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"VisionPrescription","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/VisionPrescription","title":"VisionPrescription","type":"topic","abstract":[]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Metadata":{"navigatorTitle":[{"text":"Metadata","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/digimehealthkit\/metadata","type":"topic","abstract":[],"title":"Metadata","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Metadata","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Metadata"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ActivitySummaryCompletionHandler":{"title":"ActivitySummaryCompletionHandler","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummaryCompletionHandler","type":"topic","url":"\/documentation\/digimehealthkit\/activitysummarycompletionhandler","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivitySummaryCompletionHandler"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActivitySummaryCompletionHandler"}],"abstract":[]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SampleType":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SampleType","abstract":[],"title":"SampleType","url":"\/documentation\/digimehealthkit\/sampletype","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SampleType"}],"navigatorTitle":[{"kind":"identifier","text":"SampleType"}],"type":"topic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SourceCompletionHandler":{"navigatorTitle":[{"kind":"identifier","text":"SourceCompletionHandler"}],"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SourceCompletionHandler","url":"\/documentation\/digimehealthkit\/sourcecompletionhandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceCompletionHandler"}],"title":"SourceCompletionHandler","abstract":[],"type":"topic","role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/UnitConvertable":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/UnitConvertable","url":"\/documentation\/digimehealthkit\/unitconvertable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnitConvertable"}],"navigatorTitle":[{"kind":"identifier","text":"UnitConvertable"}],"abstract":[],"title":"UnitConvertable","type":"topic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/StatisticsCollectionQuery":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatisticsCollectionQuery","kind":"identifier"}],"abstract":[{"inlineContent":[{"type":"text","text":"HKStatisticsCollectionQuery"}],"type":"strong"},{"text":" typealias","type":"text"}],"type":"topic","url":"\/documentation\/digimehealthkit\/statisticscollectionquery","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatisticsCollectionQuery","role":"symbol","navigatorTitle":[{"text":"StatisticsCollectionQuery","kind":"identifier"}],"kind":"symbol","title":"StatisticsCollectionQuery"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Category":{"navigatorTitle":[{"text":"Category","kind":"identifier"}],"kind":"symbol","title":"Category","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Category"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Category","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/digimehealthkit\/category"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/QuantityType":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/QuantityType","kind":"symbol","role":"symbol","abstract":[{"text":"All HealthKit qunatitiy types","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"QuantityType","kind":"identifier"}],"type":"topic","url":"\/documentation\/digimehealthkit\/quantitytype","navigatorTitle":[{"text":"QuantityType","kind":"identifier"}],"title":"QuantityType"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HeartbeatSeriesResultsDataHandler":{"type":"topic","title":"HeartbeatSeriesResultsDataHandler","kind":"symbol","abstract":[],"url":"\/documentation\/digimehealthkit\/heartbeatseriesresultsdatahandler","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HeartbeatSeriesResultsDataHandler","navigatorTitle":[{"text":"HeartbeatSeriesResultsDataHandler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeartbeatSeriesResultsDataHandler"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/StatisticsCompletionHandler":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatisticsCompletionHandler","url":"\/documentation\/digimehealthkit\/statisticscompletionhandler","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatisticsCompletionHandler","kind":"identifier"}],"navigatorTitle":[{"text":"StatisticsCompletionHandler","kind":"identifier"}],"title":"StatisticsCompletionHandler"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/WorkoutType":{"kind":"symbol","role":"symbol","url":"\/documentation\/digimehealthkit\/workouttype","abstract":[{"type":"text","text":"All HealthKit workout types"}],"title":"WorkoutType","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"WorkoutType","kind":"identifier"}],"navigatorTitle":[{"text":"WorkoutType","kind":"identifier"}],"type":"topic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CategoryType":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CategoryType","type":"topic","abstract":[{"text":"All HealthKit category types","type":"text"}],"url":"\/documentation\/digimehealthkit\/categorytype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CategoryType","kind":"identifier"}],"navigatorTitle":[{"text":"CategoryType","kind":"identifier"}],"role":"symbol","title":"CategoryType","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SourceQuery":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SourceQuery","url":"\/documentation\/digimehealthkit\/sourcequery","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceQuery"}],"navigatorTitle":[{"text":"SourceQuery","kind":"identifier"}],"abstract":[{"inlineContent":[{"type":"text","text":"HKSourceQuery"}],"type":"strong"},{"type":"text","text":" typealias"}],"title":"SourceQuery","type":"topic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/WorkoutEvent":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutEvent","type":"topic","abstract":[],"url":"\/documentation\/digimehealthkit\/workoutevent","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WorkoutEvent"}],"navigatorTitle":[{"text":"WorkoutEvent","kind":"identifier"}],"role":"symbol","title":"WorkoutEvent","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SampleResultsHandler":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SampleResultsHandler","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SampleResultsHandler","kind":"symbol","type":"topic","title":"SampleResultsHandler","navigatorTitle":[{"kind":"identifier","text":"SampleResultsHandler"}],"role":"symbol","url":"\/documentation\/digimehealthkit\/sampleresultshandler"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitFilesDataService":{"abstract":[],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitFilesDataService","type":"topic","kind":"symbol","url":"\/documentation\/digimehealthkit\/healthkitfilesdataservice","navigatorTitle":[{"kind":"identifier","text":"HealthKitFilesDataService"}],"role":"symbol","title":"HealthKitFilesDataService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HealthKitFilesDataService","kind":"identifier"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SampleQuery":{"url":"\/documentation\/digimehealthkit\/samplequery","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SampleQuery","abstract":[{"type":"strong","inlineContent":[{"text":"HKSampleQuery","type":"text"}]},{"type":"text","text":" typealias"}],"navigatorTitle":[{"kind":"identifier","text":"SampleQuery"}],"title":"SampleQuery","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SampleQuery","kind":"identifier"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/WorkoutConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WorkoutConfiguration"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutConfiguration","navigatorTitle":[{"kind":"identifier","text":"WorkoutConfiguration"}],"abstract":[],"title":"WorkoutConfiguration","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/digimehealthkit\/workoutconfiguration"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Characteristic":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Characteristic"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Characteristic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Characteristic"}],"title":"Characteristic","kind":"symbol","type":"topic","url":"\/documentation\/digimehealthkit\/characteristic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Correlation":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Correlation","abstract":[],"url":"\/documentation\/digimehealthkit\/correlation","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Correlation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Correlation"}],"title":"Correlation"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/DigiMeHealthKit":{"type":"topic","title":"DigiMeHealthKit Module","kind":"article","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DigiMeHealthKit"},{"text":" module is a specialized extension of the Digi.me SDK tailored for applications that require access to health-related data via Apple’s HealthKit.","type":"text"}],"url":"\/documentation\/digimehealthkit\/digimehealthkit","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKit","role":"article"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitManager":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitManager","type":"topic","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"HealthKitManager"}]},{"text":" class for HK managing operations","type":"text"}],"url":"\/documentation\/digimehealthkit\/healthkitmanager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HealthKitManager","kind":"identifier"}],"navigatorTitle":[{"text":"HealthKitManager","kind":"identifier"}],"role":"symbol","title":"HealthKitManager","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/AnchoredObjectQuery":{"url":"\/documentation\/digimehealthkit\/anchoredobjectquery","title":"AnchoredObjectQuery","type":"topic","abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"HKAnchoredObjectQuery"}]},{"text":" typealias","type":"text"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnchoredObjectQuery"}],"kind":"symbol","navigatorTitle":[{"text":"AnchoredObjectQuery","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/AnchoredObjectQuery"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/DigiMeHealthKitVersionString":{"type":"topic","title":"DigiMeHealthKitVersionString","kind":"symbol","abstract":[{"text":"Project version string for DigiMeHealthKit.","type":"text"}],"url":"\/documentation\/digimehealthkit\/digimehealthkitversionstring","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKitVersionString","fragments":[{"text":"DigiMeHealthKitVersionString","kind":"identifier"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CorrelationCompletionHandler":{"type":"topic","title":"CorrelationCompletionHandler","kind":"symbol","abstract":[],"url":"\/documentation\/digimehealthkit\/correlationcompletionhandler","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationCompletionHandler","navigatorTitle":[{"text":"CorrelationCompletionHandler","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CorrelationCompletionHandler"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Electrocardiogram":{"url":"\/documentation\/digimehealthkit\/electrocardiogram","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Electrocardiogram","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Electrocardiogram"}],"type":"topic","title":"Electrocardiogram","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Electrocardiogram","kind":"identifier"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Quantity":{"title":"Quantity","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Quantity","url":"\/documentation\/digimehealthkit\/quantity","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Quantity"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Quantity","kind":"identifier"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/AnchoredResultsHandler":{"abstract":[],"navigatorTitle":[{"text":"AnchoredResultsHandler","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/AnchoredResultsHandler","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"AnchoredResultsHandler","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AnchoredResultsHandler","url":"\/documentation\/digimehealthkit\/anchoredresultshandler"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/StatusCompletionBlock":{"type":"topic","navigatorTitle":[{"text":"StatusCompletionBlock","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/statuscompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusCompletionBlock","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatusCompletionBlock","title":"StatusCompletionBlock","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Foundation":{"type":"topic","abstract":[],"title":"Foundation","url":"\/documentation\/digimehealthkit\/foundation","role":"collection","kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Foundation"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKit":{"url":"\/documentation\/digimehealthkit\/healthkit","kind":"symbol","role":"collection","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKit","title":"HealthKit","type":"topic","abstract":[]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/VisionPrescriptionType":{"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/VisionPrescriptionType","navigatorTitle":[{"kind":"identifier","text":"VisionPrescriptionType"}],"url":"\/documentation\/digimehealthkit\/visionprescriptiontype","title":"VisionPrescriptionType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisionPrescriptionType","kind":"identifier"}],"abstract":[{"type":"text","text":"All HealthKit vision prescription types"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/StatisticsQuery":{"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/StatisticsQuery","abstract":[{"inlineContent":[{"type":"text","text":"HKStatisticsQuery"}],"type":"strong"},{"text":" typealias","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatisticsQuery"}],"url":"\/documentation\/digimehealthkit\/statisticsquery","title":"StatisticsQuery","navigatorTitle":[{"kind":"identifier","text":"StatisticsQuery"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SeriesType":{"url":"\/documentation\/digimehealthkit\/seriestype","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SeriesType","navigatorTitle":[{"text":"SeriesType","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SeriesType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SeriesType"}],"abstract":[{"type":"text","text":"All HealthKit series types"}],"type":"topic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ActivitySummaryQuery":{"title":"ActivitySummaryQuery","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummaryQuery","type":"topic","url":"\/documentation\/digimehealthkit\/activitysummaryquery","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivitySummaryQuery"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ActivitySummaryQuery"}],"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"HKActivitySummaryQuery"}]},{"text":" typealias","type":"text"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CorrelationResultsHandler":{"url":"\/documentation\/digimehealthkit\/correlationresultshandler","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationResultsHandler","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CorrelationResultsHandler"}],"title":"CorrelationResultsHandler","type":"topic","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CorrelationResultsHandler","kind":"identifier"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HeartbeatSeries":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeartbeatSeries"}],"url":"\/documentation\/digimehealthkit\/heartbeatseries","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeartbeatSeries"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HeartbeatSeries","title":"HeartbeatSeries","type":"topic","abstract":[]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Workout":{"role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Workout","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Workout"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Workout"}],"abstract":[],"title":"Workout","url":"\/documentation\/digimehealthkit\/workout","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit":{"url":"\/documentation\/digimehealthkit","kind":"symbol","type":"topic","title":"DigiMeHealthKit","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit","abstract":[],"role":"collection"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/UpdateFrequency":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UpdateFrequency","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/digimehealthkit\/updatefrequency","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/UpdateFrequency","role":"symbol","navigatorTitle":[{"text":"UpdateFrequency","kind":"identifier"}],"kind":"symbol","title":"UpdateFrequency"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/DeletedObject":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeletedObject"}],"type":"topic","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DeletedObject","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeletedObject"}],"url":"\/documentation\/digimehealthkit\/deletedobject","title":"DeletedObject","role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Sample":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Sample","url":"\/documentation\/digimehealthkit\/sample","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Sample"}],"navigatorTitle":[{"kind":"identifier","text":"Sample"}],"abstract":[],"type":"topic","title":"Sample"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Source":{"kind":"symbol","url":"\/documentation\/digimehealthkit\/source","abstract":[],"title":"Source","type":"topic","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Source","navigatorTitle":[{"kind":"identifier","text":"Source"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Source"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Payload":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Payload","url":"\/documentation\/digimehealthkit\/payload","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Payload","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Payload"}],"abstract":[],"type":"topic","title":"Payload"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ElectrocardiogramResultsHandler":{"title":"ElectrocardiogramResultsHandler","url":"\/documentation\/digimehealthkit\/electrocardiogramresultshandler","role":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ElectrocardiogramResultsHandler","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ElectrocardiogramResultsHandler"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ElectrocardiogramResultsHandler"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CategoryResultsHandler":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CategoryResultsHandler","title":"CategoryResultsHandler","type":"topic","abstract":[],"url":"\/documentation\/digimehealthkit\/categoryresultshandler","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CategoryResultsHandler"}],"role":"symbol","navigatorTitle":[{"text":"CategoryResultsHandler","kind":"identifier"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CharacteristicType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CharacteristicType","kind":"identifier"}],"abstract":[{"text":"All HealthKit characteristic types","type":"text"}],"type":"topic","url":"\/documentation\/digimehealthkit\/characteristictype","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CharacteristicType","role":"symbol","navigatorTitle":[{"text":"CharacteristicType","kind":"identifier"}],"kind":"symbol","title":"CharacteristicType"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitObserver":{"type":"topic","navigatorTitle":[{"text":"HealthKitObserver","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/healthkitobserver","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HealthKitObserver"}],"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitObserver","title":"HealthKitObserver","abstract":[{"inlineContent":[{"type":"text","text":"HealthKitObserver"}],"type":"strong"},{"type":"text","text":" class for HK observing operations"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ObserverUpdateHandler":{"kind":"symbol","title":"ObserverUpdateHandler","url":"\/documentation\/digimehealthkit\/observerupdatehandler","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ObserverUpdateHandler","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ObserverUpdateHandler","navigatorTitle":[{"kind":"identifier","text":"ObserverUpdateHandler"}],"type":"topic","role":"symbol","abstract":[]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CorrelationQuery":{"abstract":[{"type":"strong","inlineContent":[{"type":"text","text":"HKCorrelationQuery"}]},{"type":"text","text":" typealias"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CorrelationQuery"}],"type":"topic","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationQuery","kind":"symbol","role":"symbol","url":"\/documentation\/digimehealthkit\/correlationquery","title":"CorrelationQuery","navigatorTitle":[{"text":"CorrelationQuery","kind":"identifier"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Swift":{"title":"Swift","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Swift","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/digimehealthkit\/swift","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/CorrelationType":{"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/CorrelationType","navigatorTitle":[{"text":"CorrelationType","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/correlationtype","title":"CorrelationType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CorrelationType"}],"abstract":[{"text":"All HealthKit correlation types","type":"text"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/PreferredUnit":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/PreferredUnit","navigatorTitle":[{"text":"PreferredUnit","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/preferredunit","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreferredUnit"}],"type":"topic","role":"symbol","kind":"symbol","title":"PreferredUnit"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitReader":{"title":"HealthKitReader","url":"\/documentation\/digimehealthkit\/healthkitreader","type":"topic","abstract":[{"inlineContent":[{"type":"text","text":"HealthKitReader"}],"type":"strong"},{"text":" class for HK reading operations","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HealthKitReader","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"HealthKitReader","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitReader"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ActivitySummaryType":{"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummaryType","navigatorTitle":[{"text":"ActivitySummaryType","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/activitysummarytype","type":"topic","title":"ActivitySummaryType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActivitySummaryType","kind":"identifier"}],"abstract":[{"text":"All HealthKit activity summary types","type":"text"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/WorkoutResultsHandler":{"type":"topic","title":"WorkoutResultsHandler","kind":"symbol","abstract":[],"url":"\/documentation\/digimehealthkit\/workoutresultshandler","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutResultsHandler","navigatorTitle":[{"text":"WorkoutResultsHandler","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"WorkoutResultsHandler","kind":"identifier"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ObjectType":{"kind":"symbol","role":"symbol","url":"\/documentation\/digimehealthkit\/objecttype","abstract":[],"title":"ObjectType","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ObjectType","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObjectType"}],"navigatorTitle":[{"kind":"identifier","text":"ObjectType"}],"type":"topic"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitService":{"title":"HealthKitService","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HealthKitService"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitService","type":"topic","navigatorTitle":[{"text":"HealthKitService","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/healthkitservice","abstract":[{"type":"strong","inlineContent":[{"text":"HealthKitService","type":"text"}]},{"text":" class for HK easy integration","type":"text"}],"kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Statistics":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Statistics","type":"topic","abstract":[],"url":"\/documentation\/digimehealthkit\/statistics","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Statistics","kind":"identifier"}],"navigatorTitle":[{"text":"Statistics","kind":"identifier"}],"role":"symbol","title":"Statistics","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Device":{"title":"Device","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Device"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Device","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Device"}],"url":"\/documentation\/digimehealthkit\/device","abstract":[],"kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/WorkoutRouteResultsDataHandler":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutRouteResultsDataHandler","url":"\/documentation\/digimehealthkit\/workoutrouteresultsdatahandler","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"WorkoutRouteResultsDataHandler"}],"navigatorTitle":[{"kind":"identifier","text":"WorkoutRouteResultsDataHandler"}],"abstract":[],"type":"topic","title":"WorkoutRouteResultsDataHandler"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthKitWriter":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/digimehealthkit\/healthkitwriter","abstract":[{"inlineContent":[{"text":"HealthKitWriter","type":"text"}],"type":"strong"},{"type":"text","text":" class for HK writing operations"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthKitWriter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HealthKitWriter"}],"navigatorTitle":[{"text":"HealthKitWriter","kind":"identifier"}],"title":"HealthKitWriter"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/QuantityResultsHandler":{"type":"topic","title":"QuantityResultsHandler","kind":"symbol","abstract":[],"url":"\/documentation\/digimehealthkit\/quantityresultshandler","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/QuantityResultsHandler","navigatorTitle":[{"text":"QuantityResultsHandler","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QuantityResultsHandler"}],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/DocumentType":{"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DocumentType","navigatorTitle":[{"kind":"identifier","text":"DocumentType"}],"url":"\/documentation\/digimehealthkit\/documenttype","type":"topic","title":"DocumentType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"All HealthKit document types"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ElectrocardiogramType":{"type":"topic","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ElectrocardiogramType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ElectrocardiogramType"}],"abstract":[{"type":"text","text":"All HealthKit electrocardiogram types"}],"navigatorTitle":[{"kind":"identifier","text":"ElectrocardiogramType"}],"title":"ElectrocardiogramType","role":"symbol","url":"\/documentation\/digimehealthkit\/electrocardiogramtype"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/SourceRevision":{"title":"SourceRevision","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceRevision"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/SourceRevision","type":"topic","navigatorTitle":[{"text":"SourceRevision","kind":"identifier"}],"url":"\/documentation\/digimehealthkit\/sourcerevision","abstract":[],"kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/Query":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/Query","type":"topic","abstract":[{"inlineContent":[{"text":"HKQuery","type":"text"}],"type":"strong"},{"type":"text","text":" typealias"}],"url":"\/documentation\/digimehealthkit\/query","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Query","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Query"}],"role":"symbol","title":"Query","kind":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/ActivitySummary":{"role":"symbol","url":"\/documentation\/digimehealthkit\/activitysummary","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivitySummary","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActivitySummary"}],"kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/ActivitySummary","title":"ActivitySummary"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/WorkoutRoute":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"WorkoutRoute","kind":"identifier"}],"type":"topic","url":"\/documentation\/digimehealthkit\/workoutroute","kind":"symbol","title":"WorkoutRoute","navigatorTitle":[{"text":"WorkoutRoute","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/WorkoutRoute","abstract":[],"role":"symbol"},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/HealthDataOperationResult":{"title":"HealthDataOperationResult","identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/HealthDataOperationResult","abstract":[],"navigatorTitle":[{"text":"HealthDataOperationResult","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/digimehealthkit\/healthdataoperationresult","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HealthDataOperationResult"}]},"doc://me.digi.sdk.example.libraryhealth.DigiMeHealthKit/documentation/DigiMeHealthKit/PreferredUnitsCompeltion":{"identifier":"doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/PreferredUnitsCompeltion","type":"topic","abstract":[],"url":"\/documentation\/digimehealthkit\/preferredunitscompeltion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferredUnitsCompeltion","kind":"identifier"}],"navigatorTitle":[{"text":"PreferredUnitsCompeltion","kind":"identifier"}],"role":"symbol","title":"PreferredUnitsCompeltion","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKit"],"generated":true,"title":"Articles"},{"identifiers":["doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKitVersionNumber","doc:\/\/me.digi.sdk.example.libraryhealth.DigiMeHealthKit\/documentation\/DigiMeHealthKit\/DigiMeHealthKitVersionString"],"title":"Variables"}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}